// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPOgXkW_A0jEgKLKKF0g3-Pl7MJfF5B6s',
    appId: '1:736207614733:web:ea6525b9425b409bbbb644',
    messagingSenderId: '736207614733',
    projectId: 'mechanice-74413',
    authDomain: 'mechanice-74413.firebaseapp.com',
    storageBucket: 'mechanice-74413.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCytaLccDu3OBzzBDKSJkx5VSPWSKFy3Hg',
    appId: '1:736207614733:android:5af60b2e7b838552bbb644',
    messagingSenderId: '736207614733',
    projectId: 'mechanice-74413',
    storageBucket: 'mechanice-74413.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0SyScJ8swXPvM2B82gQL2iiL0c3yoJvU',
    appId: '1:736207614733:ios:55237019eef594dfbbb644',
    messagingSenderId: '736207614733',
    projectId: 'mechanice-74413',
    storageBucket: 'mechanice-74413.appspot.com',
    iosBundleId: 'com.example.mechanice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0SyScJ8swXPvM2B82gQL2iiL0c3yoJvU',
    appId: '1:736207614733:ios:477ec3407d4ed54bbbb644',
    messagingSenderId: '736207614733',
    projectId: 'mechanice-74413',
    storageBucket: 'mechanice-74413.appspot.com',
    iosBundleId: 'com.example.mechanice.RunnerTests',
  );
}
